### ISSUE TITLE
What is the int key in Issues data of the fake driver ?

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/go-scm#172]
https://github.com/jenkins-x/go-scm/blob/049a2db6bf534e071ca42e5891ec694a136822cf/scm/driver/fake/data.go#L5-L7

I thought it was the issue ID at first but then the value should be an issue, not an array of issues right ?
Am i missing something ?

**Comment by abayer** [comment]
I honestly have no idea! @jstrachan, do you know?

**Comment by jstrachan** [comment]
issue number? like #123 for an issue/PR number?

**Comment by jstrachan** [comment]
here's a little helper method used in some unit tests that creates a PR and registers it into the fake data so you can query it via the go-scm PullRequest API:
https://github.com/jenkins-x/jx-preview/blob/master/pkg/fakescms/fakescm.go#L11

**Comment by jstrachan** [comment]
see https://github.com/jenkins-x/jx-preview/blob/master/pkg/fakescms/fakescm.go#L41

**Comment by eddycharly** [comment]
Thanks !
I still don't really understand why the value is an array though. For cases where a PR has multiple issues ?
I am probably biased, reasoning in terms of github but maybe the model is different for other providers...

**Comment by jstrachan** [comment]
I just checked the fake code and there's no real reason right now for the `map[int][]*scm.Issue`  - we could just make it a `[]*scm.Issue` I suspect! - or just a `map[int]*scm.Issue`

**Comment by eddycharly** [comment]
How about making a `map[string]*scm.Issue` ? The `string` key being the repository.

**Comment by jstrachan** [comment]
ah yeah - thats probably what it should have been ;)

**Comment by eddycharly** [comment]
/close

Closing as the question has been answered.
