### ISSUE TITLE
Jx3 unable to create repo on gitlab using go-scm

### ISSUE THREAD

**Issue by pow-devops2020** [jenkins-x/go-scm#182]
@jstrachan and the team of jx3 have finished migration of `jx promote` and `jx project` last week using `go-scm` for all git repository operations. But when I used the lasted jx-cli to run `jx project quickstart --git-user myusername --git-token mytoken --git-kind gitlab --pr-poll-timeout 30m0s`, it failed with this error message `error: failed to create git repository myusername/projectname: json: cannot unmarshal array into Go value of type gitlab.gl_namespace`. 

I also have encountered this error: `error: failed to validate options: failed to create ScmClient: failed to find git token: could not find git token for git server mygitlaburl` when I randomly tried `jx project spring --git-kind gitlab`.

I would be very grateful if anyone can take a look at this issue.

**Comment by pow-devops2020** [comment]
is it any format issue in this function? https://github.com/pow-devops2020/go-scm/blob/e9d60129f642c51d76a2ab89e84c11e4ed9815d0/scm/driver/gitlab/gitlab.go#L120

**Comment by wy2249** [comment]
Hi, maintainers! I made a pr https://github.com/jenkins-x/go-scm/pull/192 to solve this issue, if anyone would love take a look and give it test.
