### ISSUE TITLE
Missing the PR review event

### ISSUE THREAD

**Issue by mateuszpodraza** [jenkins-x/go-scm#196]
In https://github.com/jenkins-x/go-scm/blob/893b81ab9331dd248b4f53454cd3c4eee57f7126/scm/repo.go#L83-L92

Because the review event is missing, `jx gitops webhook update` configures the PR review events on Github like so: ![image](https://user-images.githubusercontent.com/19386552/95736214-3805fe80-0c86-11eb-8b4c-7c3c1988b183.png)

Which, in turn, means that the `review_acts_as_lgtm` and `review_acts_as_approve` options in lighthouse do not work

**Comment by abayer** [comment]
I think I can get this done today.
