### ISSUE TITLE
Gitlab MergeRequestHook parser error

### ISSUE THREAD

**Issue by nekator** [jenkins-x/go-scm#300]
Parsing webhooks of object_kind merge_request results in an error.
` Failed to parse webhook: json: cannot unmarshal bool into Go struct field .object_attributes.merge_params.force_remove_source_branch of type string`

Webhook payload:
```
{
...
 "object_attributes": {
    ...
    "merge_params": {
      "force_remove_source_branch": true
    },
...
}

```

So i looked into the implemation and found that the [MergeReqeust](https://github.com/jenkins-x/go-scm/blob/main/scm/driver/gitlab/webhook.go#L616) and [PullRequest](https://github.com/jenkins-x/go-scm/blob/main/scm/driver/gitlab/webhook.go#L817) struct expects a string and not a boolean.

Is it possible that the payload from Gitlab changed with a newer Version? Or is it broken from the begining?

The testdata indicates that Gitlab send "0" and "1" instead of false and true.

**Comment by zzhzero** [comment]
Problem doesn't seem to be resolved

[gitlab issue](https://gitlab.com/gitlab-org/gitlab/-/issues/15647)
